### ISSUE TITLE
Load datasets from folders 

### ISSUE THREAD

**Issue by rtherezan** [carpentries-incubator/open-science-with-r#2]
It would be nice to have some information on how to load the datasets from our computer. 
Tks Marc!

**Comment by mgalland** [comment]
@rtherezan I have added this. 

https://carpentries-incubator.github.io/open-science-with-r/02-Rstudio/index.html#import-your-own-data

Is it enough for you?

**Comment by rtherezan** [comment]
Yes !!  It will be helpful to everyone. Tks.
