### ISSUE TITLE
duplicated 1st episode

### ISSUE THREAD

**Issue by fmichonneau** [carpentries-incubator/open-science-with-r#8]
As I was reviewing the changes with the switch to using remote themes, I noticed that there are 2 episodes "1". One comes from the Rmd file in the `_episodes` folder and the other from the `_episodes_rmd` folder. They look very similar but you may want to double check which one to keep. 

Let me know if you have any questions.

**Comment by mgalland** [comment]
Yes good point! I've removed the episode 01 in `_episodes_rmd`.
